### ISSUE TITLE
no partners to gossip with

### ISSUE THREAD

**Issue by bjmgeek** [hockeypuck/server#1]
I didn't see anything in the documentation about specifying partners to gossip with, so I copied the [conflux.recon] section of my v1 hockeypuck.conf.  However, when attempting to gossip, I see (if I set loglevel to debug) 
```DEBU[0056] no partners to gossip with                    label=gossip :11370```
in /var/log/hockeypuck/hockeypuck.log

**Comment by bjmgeek** [comment]
I also tried formatting the config file like it appears in https://github.com/cmars/conflux/blob/master/recon/settings_test.go

```		`
[conflux.recon]
httpAddr=":11371"
reconAddr=":11370"
[conflux.recon.partner.alice]
httpAddr="1.2.3.4:11371"
reconAddr="5.6.7.8:11370"
[conflux.recon.partner.bob]
httpAddr="4.3.2.1:11371"
reconAddr="8.7.6.5:11370"
```

but I got the error:
```
[{/home/bminton/public_html/programs/hockeypuck/packaging/src/github.com/hockeypuck/server/cmd/hockeypuck/main.go:36: } {/home/bminton/public_html/programs/hockeypuck/packaging/src/github.com/hockeypuck/server/settings.go:157: } {Near line 22 (last key parsed 'conflux.recon.partner.0.httpAddr'): Expected value but found 'i' instead.}]
```

**Comment by cmars** [comment]
Sorry about that, I'm still working on docs. The config keys have changed from Hockeypuck 1.x.

Here's a couple of sample configs that are used by [sample-run.sh](https://github.com/hockeypuck/server/blob/v2/cmd/hockeypuck/sample-run.sh) to quickly stand up two Hockeypuck servers that peer with each other locally:
[sample-peer1.conf](https://github.com/hockeypuck/server/blob/v2/cmd/hockeypuck/sample-peer1.conf)
[sample-peer2.conf](https://github.com/hockeypuck/server/blob/v2/cmd/hockeypuck/sample-peer2.conf)

**Comment by cmars** [comment]
@bjmgeek Let me know if following those configs as a guide works out for you.

**Comment by bjmgeek** [comment]
are peer1 and peer2 the hostnames?

**Comment by bjmgeek** [comment]
Here's my hockeypuck.conf
```
[hockeypuck]
loglevel="DEBUG"
logfile="/var/log/hockeypuck/hockeypuck.log"
indexTemplate="/var/lib/hockeypuck/templates/index.html.tmpl"
vindexTemplate="/var/lib/hockeypuck/templates/index.html.tmpl"
statsTemplate="/var/lib/hockeypuck/templates/stats.html.tmpl"
webroot="/var/lib/hockeypuck/www"

[hockeypuck.hkp]
bind="ip6-localhost:11371"

[conflux.recon]
httpAddr=":11371"
reconAddr=":11370"
[conflux.recon.peer1]
httpAddr="[2001:4830:1600:50a::2]:11371"
reconAddr="[2001:4830:1600:50a::2]:11370"

[hockeypuck.openpgp.db]
driver="postgres-jsonb"
dsn="host=ipv6.brian.minton.name user=hockeypuck dbname=hockeypuck password=XXXXXXXX sslmode=disable"
```

**Comment by cmars** [comment]
@bjmgeek The peer names (peer1, peer2) are just arbitrary logical names assigned to a peer.

Try changing your config to:
```
[hockeypuck]
loglevel="DEBUG"
logfile="/var/log/hockeypuck/hockeypuck.log"
indexTemplate="/var/lib/hockeypuck/templates/index.html.tmpl"
vindexTemplate="/var/lib/hockeypuck/templates/index.html.tmpl"
statsTemplate="/var/lib/hockeypuck/templates/stats.html.tmpl"
webroot="/var/lib/hockeypuck/www"

[hockeypuck.hkp]
bind="ip6-localhost:11371"

[hockeypuck.conflux.recon]
httpAddr=":11371"
reconAddr=":11370"

[hockeypuck.conflux.recon.peer1]
httpAddr="[2001:4830:1600:50a::2]:11371"
reconAddr="[2001:4830:1600:50a::2]:11370"

[hockeypuck.openpgp.db]
driver="postgres-jsonb"
dsn="host=ipv6.brian.minton.name user=hockeypuck dbname=hockeypuck password=XXXXXXXX sslmode=disable"
```

**Comment by bjmgeek** [comment]
I tried that, and I'm still seeing 
```DEBU[0010] no partners to gossip with                    label=gossip :11370```

**Comment by cmars** [comment]
My mistake, replace `[hockeypuck.conflux.recon.peer1]` with `[hockeypuck.conflux.recon.partner.peer1]`.

**Comment by bjmgeek** [comment]
That worked, thanks!

**Comment by cmars** [comment]
Great! Now, I've got to get those docs coming along (#2).
