### ISSUE TITLE
error starting in user space; Expected a top-level item to end with a new line, comment or EOF, but got 'x' instead

### ISSUE THREAD

**Issue by fsantiago07044** [hockeypuck/server#23]
hi,

I installed hockeypuck as per your github.io site install instructions from the apt repo on ubuntu 14.04 lts, and after configuring (as per your guide) and trying to start it in user space, i see:

 /usr/bin/hockeypuck -config /etc/hockeypuck/hockeypuck.conf
[{/build/hockeypuck-lsqW7K/hockeypuck-2.0~rc2~1437340214+54df397~trusty/src/github.com/hockeypuck/server/cmd/hockeypuck/main.go:36: } {/build/hockeypuck-lsqW7K/hockeypuck-2.0~rc2~1437340214+54df397~trusty/src/github.com/hockeypuck/server/settings.go:160: } {Near line 8 (last key parsed 'hockeypuck'): Expected a top-level item to end with a new line, comment or EOF, but got 'x' instead.}]

what does this mean? i am using the mongodb default setup and did define a ptree location in the config as well. 

i also installed go via apt as well just in case. will try it again and report back. thanks.

**Comment by fsantiago07044** [comment]
Still failed; strace here:

https://pastebin.com/tMqmYV3p

Thanks.

**Comment by cmars** [comment]
Looks like a parse error in the conf file.

**Comment by fsantiago07044** [comment]
On 2018-07-20 04:22 PM, Casey Marshall wrote:
> Looks like a parse error in the conf file.

you were correct. in your config guide, your examples for contact and 
hostname don't have double quotes around them. that was it. thanks.

is there any more documentation out there or is this pretty much it?

-- 
Fabian S.

OpenPGP:

0x643082042DC83E6D94B86C405E3DAA18A1C22D8F (new key)

***

0x3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC (to be retired, still valid)
